info:
  component: Eureka Server (Local Properties)

spring:
  application:
    name: eureka-server
  cloud:
    config:
      username: user
      password: user

server:
  port: 8761

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    waitTimeInMsWhenSyncEmpty: 0

logging:
  level:
    com.netflix: 'WARN'
    org.springframework.cloud: 'WARN'